---
- hosts: localhost
  tasks: 
    - name: Install a list of packages
      apt:
        pkg:
        - docker.io
      become: yes
      become_user: root
    - name: Container app deployment
      command: docker pull gcr.io/sandbox-259712/hello-world
    - name: Run app deployment
      command: docker run -d -p 443:5000 gcr.io/sandbox-259712/hello-world