---
- hosts: localhost
  tasks: 
    - name: Install a list of packages
      apt:
        pkg:
        - docker.io
      become: yes
      become_user: root
    - name: Pull an Image
      docker_image:
        name: gcr.io/hello-world:latest
        source: pull
        ports: 443:5000
        state: 'started'