---
- hosts: localhost
  tasks: 
    - name: Install a list of packages
      apt:
        pkg:
        - docker.io
      become: yes
      become_user: root
    - name: Container app deployment
      docker:
        name: go-app
        image: gcr.io/hello-world:latest
        ports: 443:5000
        state: 'started'